/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintProj;

import com.sun.org.apache.xerces.internal.util.XMLSymbols;
import com.sun.webkit.ColorChooser;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.annotation.processing.FilerException;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class paint extends javax.swing.JFrame {

    /**
     * Creates new form paint
     */
    Color color = Color.BLACK;
    String shape = "";
    String text;
    int size = 15;
    String ffont = "Tahoma";
    Font ff = new Font(ffont, Font.PLAIN, size);
    int x1 = 50, y1 = 50, x2 = 50, y2 = 50;

    public paint() {
        initComponents();
        this.setTitle("Paint");
        setLocationRelativeTo(null);
    //    JOptionPane.showMessageDialog(null, "Welcome "+ fnm.getText()+ ", enjoy drawing:)");
       // String nm = JOptionPane.showInputDialog(null, "Enter Your Name: ", "User Name", JOptionPane.INFORMATION_MESSAGE);
       // JOptionPane.showMessageDialog(null, "Welcome to Paint Program " + nm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        drawArea = new javax.swing.JPanel();
        goF2 = new javax.swing.JButton();
        pincle = new javax.swing.JPanel();
        colorsB = new javax.swing.JButton();
        arc = new javax.swing.JButton();
        rec = new javax.swing.JButton();
        cir = new javax.swing.JButton();
        lin = new javax.swing.JButton();
        ovRec = new javax.swing.JButton();
        blackB = new javax.swing.JButton();
        grayB = new javax.swing.JButton();
        redB = new javax.swing.JButton();
        orangeB = new javax.swing.JButton();
        greenB = new javax.swing.JButton();
        blueB = new javax.swing.JButton();
        yellowB = new javax.swing.JButton();
        darkBlueB = new javax.swing.JButton();
        purbleB = new javax.swing.JButton();
        whiteB = new javax.swing.JButton();
        darkGrayB = new javax.swing.JButton();
        pinkB = new javax.swing.JButton();
        brownB = new javax.swing.JButton();
        ligthYellowB = new javax.swing.JButton();
        darkGreenB = new javax.swing.JButton();
        cyanB = new javax.swing.JButton();
        ligthDarkBlueB = new javax.swing.JButton();
        darkPurpleB = new javax.swing.JButton();
        sqr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pincleB = new javax.swing.JButton();
        ereaseB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawArea.setBackground(new java.awt.Color(255, 255, 255));
        drawArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drawAreaMouseDragged(evt);
            }
        });
        drawArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                drawAreaMouseReleased(evt);
            }
        });

        goF2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        goF2.setText("Enter To Play ");
        goF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goF2MouseClicked(evt);
            }
        });
        goF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goF2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drawAreaLayout = new javax.swing.GroupLayout(drawArea);
        drawArea.setLayout(drawAreaLayout);
        drawAreaLayout.setHorizontalGroup(
            drawAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goF2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        drawAreaLayout.setVerticalGroup(
            drawAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawAreaLayout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(goF2))
        );

        colorsB.setIcon(new javax.swing.ImageIcon("C:\\Uni\\Java\\GUI\\finalProj\\colorsIcon.png")); // NOI18N
        colorsB.setIconTextGap(5);
        colorsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorsBActionPerformed(evt);
            }
        });

        arc.setText("Arc");
        arc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcActionPerformed(evt);
            }
        });

        rec.setText("Rectangle");
        rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recActionPerformed(evt);
            }
        });

        cir.setText("Circle");
        cir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cirActionPerformed(evt);
            }
        });

        lin.setText("Line");
        lin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linActionPerformed(evt);
            }
        });

        ovRec.setText("Oval Rectangle");
        ovRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovRecActionPerformed(evt);
            }
        });

        blackB.setBackground(new java.awt.Color(0, 0, 0));
        blackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackBActionPerformed(evt);
            }
        });

        grayB.setBackground(new java.awt.Color(153, 153, 153));
        grayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayBActionPerformed(evt);
            }
        });

        redB.setBackground(new java.awt.Color(204, 0, 0));
        redB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBActionPerformed(evt);
            }
        });

        orangeB.setBackground(new java.awt.Color(255, 102, 0));
        orangeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeBActionPerformed(evt);
            }
        });

        greenB.setBackground(new java.awt.Color(51, 255, 0));
        greenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenBActionPerformed(evt);
            }
        });

        blueB.setBackground(new java.awt.Color(51, 153, 255));
        blueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBActionPerformed(evt);
            }
        });

        yellowB.setBackground(new java.awt.Color(255, 255, 0));
        yellowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowBActionPerformed(evt);
            }
        });

        darkBlueB.setBackground(new java.awt.Color(0, 0, 204));
        darkBlueB.setActionCommand("darkBlueB");
        darkBlueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkBlueBActionPerformed(evt);
            }
        });

        purbleB.setBackground(new java.awt.Color(153, 0, 153));
        purbleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purbleBActionPerformed(evt);
            }
        });

        whiteB.setBackground(new java.awt.Color(255, 255, 255));
        whiteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteBActionPerformed(evt);
            }
        });

        darkGrayB.setBackground(new java.awt.Color(102, 102, 102));
        darkGrayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkGrayBActionPerformed(evt);
            }
        });

        pinkB.setBackground(new java.awt.Color(255, 0, 204));
        pinkB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkBActionPerformed(evt);
            }
        });

        brownB.setBackground(new java.awt.Color(153, 51, 0));
        brownB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownBActionPerformed(evt);
            }
        });

        ligthYellowB.setBackground(new java.awt.Color(255, 255, 153));
        ligthYellowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligthYellowBActionPerformed(evt);
            }
        });

        darkGreenB.setBackground(new java.awt.Color(0, 102, 0));
        darkGreenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkGreenBActionPerformed(evt);
            }
        });

        cyanB.setBackground(new java.awt.Color(0, 255, 255));
        cyanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyanBActionPerformed(evt);
            }
        });

        ligthDarkBlueB.setBackground(new java.awt.Color(0, 102, 153));

        darkPurpleB.setBackground(new java.awt.Color(51, 0, 51));
        darkPurpleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkPurpleBActionPerformed(evt);
            }
        });

        sqr.setText("Square");
        sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 10)); // NOI18N
        jButton1.setText("_________");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("________");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setText("____________");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pincleB.setIcon(new javax.swing.ImageIcon("C:\\Uni\\Java\\GUI\\finalProj\\pencle..png")); // NOI18N
        pincleB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pincleBMouseDragged(evt);
            }
        });
        pincleB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pincleBMouseClicked(evt);
            }
        });
        pincleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincleBActionPerformed(evt);
            }
        });

        ereaseB.setIcon(new javax.swing.ImageIcon("C:\\Uni\\Java\\GUI\\finalProj\\erease.png")); // NOI18N
        ereaseB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ereaseBMouseDragged(evt);
            }
        });
        ereaseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ereaseBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pincleLayout = new javax.swing.GroupLayout(pincle);
        pincle.setLayout(pincleLayout);
        pincleLayout.setHorizontalGroup(
            pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pincleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ereaseB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincleB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pincleLayout.createSequentialGroup()
                        .addComponent(lin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sqr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pincleLayout.createSequentialGroup()
                        .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ovRec, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(whiteB, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(blackB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addComponent(grayB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addComponent(darkGrayB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pinkB, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orangeB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brownB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addComponent(yellowB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addComponent(ligthYellowB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(darkGreenB, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cyanB, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(blueB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(darkBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pincleLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ligthDarkBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purbleB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darkPurpleB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorsB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pincleLayout.setVerticalGroup(
            pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pincleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pincleLayout.createSequentialGroup()
                            .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(blackB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(yellowB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(redB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(grayB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orangeB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(blueB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(greenB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(whiteB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(darkGrayB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pinkB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(brownB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ligthYellowB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(darkGreenB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cyanB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ligthDarkBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pincleLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(colorsB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(pincleLayout.createSequentialGroup()
                                    .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(purbleB, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addComponent(darkBlueB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(8, 8, 8)
                                    .addComponent(darkPurpleB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pincleLayout.createSequentialGroup()
                .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addComponent(pincleB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ereaseB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pincleLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arc)
                            .addComponent(sqr)
                            .addComponent(cir)
                            .addComponent(lin))
                        .addGap(2, 2, 2)
                        .addGroup(pincleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ovRec)
                            .addComponent(rec))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel4.setText("Tools");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel2.setText("Size");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel1.setText("Colors");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel3.setText("Shapes");

        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("New");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Open");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Save");
        jMenu1.add(jMenuItem6);

        jMenu4.setText("Save As");

        jMenuItem7.setText("PNG Picture");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("GIF Picture");
        jMenu4.add(jMenuItem8);

        jMenu1.add(jMenu4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Back to Login Form");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("save");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("save");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("save as");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pincle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(155, 155, 155)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(277, 277, 277)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(pincle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Do You Want To Save Your Work? ");
        if (n == 0) {
            JOptionPane.showMessageDialog(null, "Save");
            
            
            
        }
        if (n == 1) {
            JOptionPane.showMessageDialog(null, "Dont Save");
        }
        if (n == 2) {
            JOptionPane.showMessageDialog(null, "Cancle");
        }
            repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        size = 20;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        size = 10;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        size = 5;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrActionPerformed
        Graphics s = drawArea.getGraphics();
        //s.drawSquare(300, 200, 200, 100);
        shape = "square";
    }//GEN-LAST:event_sqrActionPerformed

    private void cyanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyanBActionPerformed
        color = color.CYAN;
    }//GEN-LAST:event_cyanBActionPerformed

    private void brownBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownBActionPerformed
        color = new Color(153, 51, 0);
    }//GEN-LAST:event_brownBActionPerformed

    private void pinkBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkBActionPerformed
        color = color.PINK;
    }//GEN-LAST:event_pinkBActionPerformed

    private void darkGrayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkGrayBActionPerformed
        color = new Color(102, 102, 102);
    }//GEN-LAST:event_darkGrayBActionPerformed

    private void whiteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteBActionPerformed
        color = color.WHITE;
    }//GEN-LAST:event_whiteBActionPerformed

    private void purbleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purbleBActionPerformed
        color = new Color(153, 0, 153);
    }//GEN-LAST:event_purbleBActionPerformed

    private void darkBlueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkBlueBActionPerformed
        color = new Color(0, 102, 153);
    }//GEN-LAST:event_darkBlueBActionPerformed

    private void blueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBActionPerformed
        color = color.BLUE;
    }//GEN-LAST:event_blueBActionPerformed

    private void greenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenBActionPerformed
        color = color.GREEN;
    }//GEN-LAST:event_greenBActionPerformed

    private void orangeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeBActionPerformed
        color = color.ORANGE;
    }//GEN-LAST:event_orangeBActionPerformed

    private void redBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBActionPerformed
        color = color.RED;
    }//GEN-LAST:event_redBActionPerformed

    private void grayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayBActionPerformed
        color = color.GRAY;
    }//GEN-LAST:event_grayBActionPerformed

    private void blackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackBActionPerformed
        color = color.BLACK;
    }//GEN-LAST:event_blackBActionPerformed

    private void ovRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovRecActionPerformed
        Graphics ovrec = this.getGraphics();
       //  ovrec.drawRoundRect(500, 400, 300, 200, 270);
    }//GEN-LAST:event_ovRecActionPerformed

    private void linActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linActionPerformed
        Graphics l = drawArea.getGraphics();
        l.drawLine(300, 200, 200, 100);
        shape = "line";
    }//GEN-LAST:event_linActionPerformed

    private void cirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cirActionPerformed
        Graphics o = drawArea.getGraphics();
        o.drawOval(300, 200, 200, 100);
        shape = "oval";
    }//GEN-LAST:event_cirActionPerformed

    private void recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recActionPerformed
        Graphics re = drawArea.getGraphics();
        re.drawLine(300, 200, 200, 100);
        shape = "rectangle";
    }//GEN-LAST:event_recActionPerformed

    private void arcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcActionPerformed
        Graphics a = drawArea.getGraphics();
        a.drawArc(300, 200, 200, 100, 200, 270);
        shape = "arc";
    }//GEN-LAST:event_arcActionPerformed

    private void colorsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorsBActionPerformed
        JColorChooser c = new JColorChooser();
        Color c1 = c.getColor();
        //  c.setVisible(true);
        c1 = JColorChooser.showDialog(this, "Choose", Color.red);
        drawArea.setBackground(c1);

    }//GEN-LAST:event_colorsBActionPerformed

    private void ereaseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ereaseBActionPerformed

    }//GEN-LAST:event_ereaseBActionPerformed

    private void ereaseBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ereaseBMouseDragged
        int xx1, yy1;
        xx1 = evt.getX();
        yy1 = evt.getY();
        Graphics g = drawArea.getGraphics();
        g.setColor(new java.awt.Color(255, 255, 255));
        g.fillRect(xx1, yy1, 30, 30);
    }//GEN-LAST:event_ereaseBMouseDragged

    private void pincleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincleBActionPerformed
        size = 5;
    }//GEN-LAST:event_pincleBActionPerformed

    private void goF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goF2ActionPerformed

    private void goF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goF2MouseClicked
        this.setVisible(false);
        playGame g = new playGame();
        g.setVisible(true);
    }//GEN-LAST:event_goF2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked
    private void pincleBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pincleBMouseDragged

    }//GEN-LAST:event_pincleBMouseDragged

    private void drawAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawAreaMouseDragged
        x2 = evt.getX();
        y2 = evt.getY();
        Graphics g = drawArea.getGraphics();
        g.setColor(color);
        g.fillOval(x2, y2, size, size);
        switch (shape) {
            case "line": {
                g.drawLine(x1, y1, x2, y2);
                repaint();
                break;
            }
            case "oval": {
                g.fillOval(x1, y1, x2, y2);
                repaint();
                break;
            }
             case "arc": {
                g.fillArc(x1, y1, x2, y2, 88, 270);
                repaint();
                break;
            }
            case "rectangle": {
                g.fillRect(x1, y1, x2, y2);
                repaint();
                break;
            }
        }
    }//GEN-LAST:event_drawAreaMouseDragged

    private void pincleBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pincleBMouseClicked

    }//GEN-LAST:event_pincleBMouseClicked
    private void drawAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawAreaMousePressed
        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_drawAreaMousePressed

    private void drawAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawAreaMouseReleased
        Graphics g = drawArea.getGraphics();
        g.setColor(color);
        switch (shape) {
            case "line": {
                g.drawLine(x1, y1, x2, y2);
            }
            default: {
                g.fillOval(x2, y2, size, size);
            }
        }
    }//GEN-LAST:event_drawAreaMouseReleased

    private void darkPurpleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkPurpleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_darkPurpleBActionPerformed

    private void darkGreenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkGreenBActionPerformed
          color = new Color(0, 102, 0);
    }//GEN-LAST:event_darkGreenBActionPerformed

    private void yellowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowBActionPerformed
           color = new Color(255, 255, 0);
    }//GEN-LAST:event_yellowBActionPerformed

    private void ligthYellowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligthYellowBActionPerformed
           color = new Color(255, 255, 153);
    }//GEN-LAST:event_ligthYellowBActionPerformed
        int choosing, img=0;
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser fc= new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("JPG & GIF & PNG", "JPG", "GIF", "PNG");
        fc.setFileFilter(filter);
        choosing= fc.showOpenDialog(this);
        String file= (""+ fc.getSelectedFile());
        ImageIcon getImage= new ImageIcon(file);
          if(choosing== JFileChooser.APPROVE_OPTION){
            //   drawArea.setText(drawArea.getText()+ "\n"+ fc.getSelectedFile().getName());
      //         drawArea.setIcon(getImage);
          }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        login log= new login();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arc;
    private javax.swing.JButton blackB;
    private javax.swing.JButton blueB;
    private javax.swing.JButton brownB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cir;
    private javax.swing.JButton colorsB;
    private javax.swing.JButton cyanB;
    private javax.swing.JButton darkBlueB;
    private javax.swing.JButton darkGrayB;
    private javax.swing.JButton darkGreenB;
    private javax.swing.JButton darkPurpleB;
    private javax.swing.JPanel drawArea;
    private javax.swing.JButton ereaseB;
    private javax.swing.JButton goF2;
    private javax.swing.JButton grayB;
    private javax.swing.JButton greenB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton ligthDarkBlueB;
    private javax.swing.JButton ligthYellowB;
    private javax.swing.JButton lin;
    private javax.swing.JButton orangeB;
    private javax.swing.JButton ovRec;
    private javax.swing.JPanel pincle;
    private javax.swing.JButton pincleB;
    private javax.swing.JButton pinkB;
    private javax.swing.JButton purbleB;
    private javax.swing.JButton rec;
    private javax.swing.JButton redB;
    private javax.swing.JButton sqr;
    private javax.swing.JButton whiteB;
    private javax.swing.JButton yellowB;
    // End of variables declaration//GEN-END:variables

    void setSize(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
